# Generated by Django 6.0.4 on 2026-07-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_convidado', models.CharField(max_length=150, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('vai_comparecer', models.BooleanField(verbose_name='vai comparecer')),
                ('quantidade_acompanhantes', models.PositiveSmallIntegerField(default=0, verbose_name='quantidade de acompanhantes')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'confirmação de presença',
                'verbose_name_plural': 'confirmações de presença',
                'ordering': ['-criado_em'],
            },
        ),
    ]
