# Generated by Django 6.0.4 on 2026-07-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=100, verbose_name='nome')),
                ('mensagem', models.TextField(max_length=500, verbose_name='recado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'recado',
                'verbose_name_plural': 'recados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
