# Generated by Django 6.0.4 on 2026-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0002_recado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recado',
            name='mensagem',
            field=models.TextField(max_length=300, verbose_name='recado'),
        ),
    ]
