# Generated by Django 6.0.4 on 2026-07-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convite', '0003_alter_recado_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacao',
            name='quantidade_acompanhantes',
        ),
    ]
